### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by wiktorkisielewski** [witkiewiczmikolaj/helbreder#9]
It would be cool to introduce a dark mode, with dark/light switch somewhere on the website

**Comment by witkiewiczmikolaj** [comment]
Consider it done

**Comment by witkiewiczmikolaj** [comment]
Done:  
https://github.com/witkiewiczmikolaj/helbreder/blob/892976c2c54864ca7b8c59afaf6261ef24d0b24c/core/app/templates/index.html#L67
